const sampleData = {
  products: [
    {
      name: "Ballerina",
      tags: "woman-dancer-ballet-blonde",
      category: "Mixed Media",
      description:
        "A classic ballerina captured in a kneeling pose. The original was created with alcohol markers and colored pencils on artist paper.",
      images: [
        "/images/sample-products/Ballerina.jpg",
        "/images/sample-products/Ballerina copy.jpg",
      ],
      original: true,
      originalPrice: 250,
      printStartPrice: 150,
      substrate: "Artist Paper",
      dimension: "11x14",
      portrait: true,
      artist: "Mary",
      rating: 4.5,
      numReviews: 10,
      isFeatured: true,
    },
    {
      name: "Dance Practice",
      tags: "woman-dancing-studio-ballet",
      category: "Mixed Media",
      description:
        "A young woman practicing dance. The original was created with alcohol markers and colored pencils on artist paper.",
      images: [
        "/images/sample-products/DancePractice.jpg",
        "/images/sample-products/DancePractice copy.jpg",
      ],
      original: true,
      originalPrice: 250,
      printStartPrice: 150,
      substrate: "Artist Paper",
      dimension: "11x14",
      portrait: true,
      artist: "Mary",
      rating: 3.5,
      numReviews: 8,
      isFeatured: false,
    },

    {
      name: "Dreamy Dancer",
      tags: "woman-dancer-impressionist-abstract-blonde",
      category: "Mixed Media",
      description:
        "A young woman is dancing in a jumping pose. The textured background is playfully painted with acrylic paints and inks. This work is created mostly with acrylic paints with touches of neocolor pastels.The original is painted on  artist paper.",
      images: [
        "/images/sample-products/DreamyDancer.jpg",
        "/images/sample-products/DreamyDancer copy.jpg",
      ],
      original: true,
      originalPrice: 250,
      printStartPrice: 150,
      substrate: "Artist Paper",
      dimension: "11x14",
      portrait: true,
      artist: "Mary",
      rating: 4.5,
      numReviews: 10,
      isFeatured: true,
    },
    {
      name: "Dancer",
      tags: "woman-dancing-intense-brunette-mauve",
      category: "Acrylic",
      description:
        "A young woman dancing created with acrylic paints and inks. The original is painted on  artist paper.",
      images: [
        "/images/sample-products/Dancer.jpg",
        "/images/sample-products/Dancer copy.jpg",
      ],
      original: true,
      originalPrice: 250,
      printStartPrice: 150,
      substrate: "Artist Paper",
      dimension: "11x14",
      portrait: true,
      artist: "Mary",
      rating: 4.5,
      numReviews: 10,
      isFeatured: false,
    },
    {
      name: "Giraffe",
      tags: "zoo-animal-cute-foliage",
      category: "Oil Pastel",
      description:
        "A giraffe's profile portrait is majestically drawn with oil pastels. The original is not available.",
      images: [
        "/images/sample-products/Giraffe.jpg",
        "/images/sample-products/Giraffe copy.jpg",
      ],
      original: false,
      originalPrice: null,
      printStartPrice: 150,
      substrate: null,
      dimension: null,
      portrait: true,
      artist: "Mary",
      rating: 4.0,
      numReviews: 6,
      isFeatured: true,
    },
    {
      name: "Fox Cub",
      tags: "wild-animal-cute-red",
      category: "Digital",
      description:
        "A fox cub portrait digitally painted impressionistically. The original is not available.",
      images: [
        "/images/sample-products/FoxCub.jpg",
        "/images/sample-products/FoxCub copy.jpg",
      ],
      original: false,
      originalPrice: null,
      printStartPrice: 150,
      substrate: null,
      dimension: null,
      portrait: true,
      artist: "Mary",
      rating: 4.5,
      numReviews: 6,
      isFeatured: true,
    },
  ],
};

export default sampleData;
